# ~/.config/starship.toml
# https://starship.rs/config

add_newline = false

[directory]
truncation_length = 5
truncation_symbol = '…/'

[sudo]
disabled = false
style = 'bold red'

[git_status]
# Remove the stash status, as I always have stuff stashed
format = '([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style) )'
