" vim-plug {{{
" Install vim-plug if it isn't yet
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" List plugins
call plug#begin('~/.vim/plugged')

" Big functionalities
Plug 'vimwiki/vimwiki'              " Wiki notetaking in vim
Plug 'Yggdroot/LeaderF'             " Fuzzy finder
Plug 'majutsushi/tagbar'            " Lists the file's tags
Plug 'ludovicchabant/vim-gutentags' " Manages tags file for us (important for <C-i>)

" Vim lines
Plug 'itchyny/lightline.vim'        " Light status line
Plug 'mgee/lightline-bufferline'    " Bufferline for lightline

" Git
Plug 'tpope/vim-fugitive'     " git integration in vim
Plug 'airblade/vim-gitgutter' " git diff in the gutter

" Syntax
Plug 'scrooloose/syntastic'                             " Syntax checker (synchronous, but awesome)
Plug 'Rip-Rip/clang_complete', {'for': ['cpp', 'c']}    " C/C++ autocomplete
Plug 'sheerun/vim-polyglot'                             " 100+ languages syntax highlight

" Style
Plug 'editorconfig/editorconfig-vim'                    " Have vim adapt to different projects
Plug 'godlygeek/tabular'                                " Aligns things
Plug 'raimondi/delimitmate'                             " Auto-pairs parenses and other things
Plug 'ap/vim-css-color', {'for': ['html', 'css', 'js']} " Preview colours in the file

" General additions
Plug 'ervandew/supertab'    " Easy tab completion
Plug 'markonm/traces.vim'   " Shows preview for Ex commands
Plug 'tpope/vim-surround'   " Add object for surrounding elements
Plug 'tpope/vim-commentary' " Auto-comment with gc
Plug 'tpope/vim-repeat'     " Add . command support for plugins

" Tmux
Plug 'christoomey/vim-tmux-navigator' " Navigating from vim and tmux panes
Plug 'epeli/slimux'                   " tmux helper for REPL and shell

" Looks
Plug 'morhetz/gruvbox'           " A theme inspired by solarized
Plug 'romainl/Apprentice'        " Nice theme, yés good
Plug 'sheerun/vim-wombat-scheme' " Simple dark theme

call plug#end()
" automatic filetype plugin indent on and syntax enable
"}}}

" Plugins config{{{
" vimwiki{{{
let wiki = {}
let wiki.path = '~/Notebooks/vimwiki/'
let wiki.syntax = 'markdown'
let wiki.ext = '.Rmd'
let wiki.nested_syntaxes = {'python': 'python', 'c++': 'cpp', 'sh': 'sh', 'R': 'R', 'c': 'c', 'tex': 'tex'}
" heig wiki parameters
let heig = {}
let heig.path = '~/Notebooks/HEIGWiki/'
let heig.syntax = 'markdown'
let heig.ext = '.Rmd'
let heig.nested_syntaxes = wiki.nested_syntaxes
" vimwiki dictionary of wikis
let g:vimwiki_list = [wiki, heig]
" vimwiki parameters
let g:vimwiki_folding = 'expr'
let g:vimwiki_conceallevel = 0
let g:vimwiki_global_ext = 0

" Handle [[vfile:...]] links in a simple new buffer{{{
function! VimwikiLinkHandler(link)
" Use Vim to open external files with the 'vfile:' scheme.  E.g.:
"   1) [[vfile:~/Code/PythonProject/abc123.py]]
"   2) [[vfile:./|Wiki Home]]
let link = a:link
if link =~# '^vfile:'
let link = link[1:]
else
return 0
endif
let link_infos = vimwiki#base#resolve_link(link)
if link_infos.filename == ''
echomsg 'Vimwiki Error: Unable to resolve link!'
return 0
else
exe 'edit ' . fnameescape(link_infos.filename)
return 1
endif
endfunction"}}}
"}}}

" Syntastic{{{
let g:syntastic_mode_map = {
    \ "mode": "active",
    \ "active_filetypes": ["cpp", "c", "python"],
    \ "passive_filetypes": ["tex"] }
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" cpp
let g:syntastic_cpp_compiler_options = '-std=c++11 -Wall -Wconversion -Wextra -pedantic'
let g:syntastic_cpp_check_header = 1


"}}}

" Leaderf
let g:Lf_ShowHidden=1
let g:Lf_MruFileExclude = ['*.so', '*.class', '*.out']

" Supertab
" let g:SuperTabDefaultCompletionType = "context"

" Tagbar
let g:tagbar_map_showproto = "f"		" f to show function's prototype
let g:tagbar_map_togglefold = "<Space>"
let g:tagbar_width = 40
let g:tagbar_sort = 0
let g:tagbar_autofocus = 1

" delimitMate
let g:delimitMate_expand_cr = 1
let g:delimitMate_expand_space = 1

" GitGutter
let g:gitgutter_map_keys = 0

" RipClang
let g:clang_library_path = '/usr/lib/libclang.so'
let g:clang_user_options = '-std=c++11'

" javacomplete2
" autocmd FileType java setlocal omnifunc=javacomplete#Complete
" let g:JavaComplete_EnableDefaultMappings = 0
"}}}

" Looks{{{
" Colorschemes config
let g:gruvbox_contrast_light = 'hard'
let g:gruvbox_italic=1

set background=dark
colorscheme apprentice

" Add bad spelling highlighting
highlight clear SpellBad
highlight SpellBad ctermfg=red guifg=red

" Lightline
set laststatus=2        " Always show status bar
set showtabline=2	" Always show tab bar
let g:lightline = {
\ 'colorscheme': 'wombat',
\ 'active': {
\   'left': [ [ 'mode', 'paste' ],
\             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
\ },
\ 'component_function': {
\   'gitbranch': 'fugitive#head'
\ },
\ }
let g:lightline.tabline          = {'left': [['buffers']]}
let g:lightline.component_expand = {'buffers': 'lightline#bufferline#buffers'}
let g:lightline.component_type   = {'buffers': 'tabsel'}
"}}}

" Options{{{
set path+=** " Tab-completion in command line
set wildmenu " Display menu showing following files

" HEIG max column count
autocmd FileType cpp,hpp,c,h,java setlocal colorcolumn=85

" GMPL syntax
autocmd BufRead,BufNewFile *.mod set syntax=gmpl

" Disable current line highlight when split not in focus
augroup line_highlight
autocmd!
autocmd BufLeave * :set nocursorline
autocmd BufEnter * :set cursorline
autocmd InsertEnter * :set cursorline
autocmd InsertLeave * :set nocursorline
augroup END

" Enable spellcheck for certain files
autocmd FileType vimwiki,markdown,gitcommit,tex setlocal spell spelllang=en,fr

" Jump to the last position when reopening a file
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Set options
let g:tex_flavor='latex'
set timeoutlen=1000 ttimeoutlen=0    " Removes the delay for escape key in tmux

" set relativenumber
set number	           " Show number line in middle of relativenumber
set splitright         " Open new splits on the right
set splitbelow         " Open new splits below, if not on the right
set scrolloff=3        " Start scrolling three lines before end
set sidescrolloff=3    " Start scrolling three columns before end
set synmaxcol=500      " Only syntax highlight the first so much columns
set confirm            " Dialog when :q, :w or :wq fails
set undofile           " Persistent undo across sessions
set hidden             " Hide buffers instead of unloading them (speeds up syntastic)
set linebreak          " Break only at word boundaries
set encoding=utf8
set fileencoding=utf8

set showcmd            " Show (partial) command in status line.
set showmatch          " Show matching brackets.
set noshowmode         " Don't show the current mode (airline)
set ignorecase         " Do case insensitive matching
set smartcase          " Do smart case matching (requires ignorecase)
set incsearch          " Incremental search
set mouse=a            " Enable mouse usage (all modes)
set wrapscan           " Searches wrap around end of file
set autoread           " Reload files changed outside vim
set notimeout          " Don't timeout after Leader for example
set ttimeout           " Don't do the previous thing for Escape

set completeopt=menu,menuone

" Set dirs for swap and others
set directory=~/.vim/swap//
set undodir=~/.vim/undo//
"}}}

" Custom mappings{{{
let mapleader = ','

" Basics{{{
" Quit / save
nnoremap <Leader>q :q<CR>
nnoremap <Leader>s :w<CR>
nnoremap <Leader>wq :wq<CR>
nnoremap <Leader>wa :wa<CR>

" Easier redo
nnoremap U <C-r>

" More logic Y
nnoremap Y y$

" Remap backtick to follow mark
noremap ' `

" Remap spell bindings
nnoremap z0 z=

" Remap increment and decrement
nnoremap <C-y> <C-x>
nnoremap <C-x> <C-a>

" Mappings for following tags (<C-p> to go back)
nnoremap <C-i> <C-]>
" Follow tag in new tab
nnoremap <C-o> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>

" Movement
nnoremap <expr> j v:count ? 'j' : 'gj'
nnoremap <expr> k v:count ? 'k' : 'gk'
nnoremap <silent> <Up> gk
nnoremap <silent> <Down> gj
nnoremap <silent> <Home> g<Home>
nnoremap <silent> <End> g<End>
inoremap <silent> <Home> <C-o>g<Home>
inoremap <silent> <End> <C-o>g<End>
noremap J }
noremap K {

" Copy and paste to and from system clipboard
noremap cy "+y
nnoremap cyy "+yy
nnoremap cp "+p
nnoremap cP "+P

" Remap play macro
nnoremap Q @q
vnoremap Q :norm @q<cr>
"}}}

" Buffers{{{
nnoremap H :bp<CR>
nnoremap L :bn<CR>

" Close buffer
nnoremap <Leader>x :bp\|bd #<CR>

" Open current buffer to the right, and change this split's
" buffer to the previous
nmap <silent> <Leader>v :vs<CR><C-h>:bp<CR><C-l>
nmap <silent> <Leader>h :sp<CR><C-k>:bp<CR><C-j>

" Resize panes
nnoremap <silent> <C-w>l :vertical resize +10<CR>
nnoremap <silent> <C-w>h :vertical resize -10<CR>
nnoremap <silent> <C-w>k :resize +10<CR>
nnoremap <silent> <C-w>j :resize -10<CR>
"}}}

" Misc{{{
" Write when the file wasn't opened with sudo privileges
cmap w!! w !sudo tee % > /dev/null

" F1 to open custom bindings help
nnoremap <silent> <F1> :60vsplit $HOME/Dev/dotfiles/vim/bindings.md<CR>

" Toggles for features
nnoremap <silent> <Leader>tt :TagbarToggle<CR>
nnoremap <F4> :GitGutterToggle<CR>
inoremap <F4> <Esc> :GitGutterToggle<CR>gi
nnoremap <F6> :setlocal spell! spelllang=en,fr<CR>
inoremap <F6> <Esc>:setlocal spell! spelllang=en,fr<CR>gi
nnoremap <F7> :TagbarToggle<CR>
inoremap <F7> <Esc>:TagbarToggle<CR>gi
nnoremap <F8> :SyntasticToggleMode<CR>
inoremap <F8> <Esc>:SyntasticToggleMode<CR>gi
"}}}

" Slimux{{{
nnoremap <Leader>tr :SlimuxREPLSendLine<CR>
vnoremap <Leader>tr :SlimuxREPLSendSelection<CR>
nnoremap <Leader>tc :SlimuxREPLConfigure<CR>
nnoremap <Leader>tp :SlimuxShellPrompt<CR>
nnoremap <Leader>tl :SlimuxShellLast<CR>
nnoremap <Leader>tf :SlimuxShellConfigure<CR>
"}}}

" Programming helpers{{{
" Go to next placeholder
nnoremap <Leader><Tab> <Esc>/<++><CR>ca<

" Insert semicolon at end of line
imap <Leader>; <Esc>A;<Esc>
nmap <Leader>; A;<Esc>

" Insert curly braces at end of line
inoremap <Leader>à <Esc>A<Space>{}<Esc>i
nnoremap <Leader>à A<Space>{}<Esc>i

" Python : Insert colon at end of line
autocmd FileType python imap <Leader>; <Esc>A:
autocmd FileType python nmap <Leader>; A:
autocmd FileType python imap <Leader>" """"""""<Esc>hhi
autocmd FileType python nmap <Leader>" i""""""""<Esc>hhi

" (R) Markdown
" Italics, bold, highlight and links
autocmd FileType vimwiki nmap <Leader>mi ysiw_
autocmd FileType vimwiki nmap <Leader>mb ysiw*lysiw*
autocmd FileType vimwiki nmap <Leader>mh ysiw`
autocmd FileType vimwiki nmap <Leader>ml a[<++>](<++>)<Esc>0
autocmd FileType vimwiki imap <Leader>ml [<++>](<++>)<Esc>B
" Code chunks
autocmd FileType vimwiki nmap <Leader>mc i````{}<CR>```<Esc>klla
autocmd FileType vimwiki imap <Leader>mc ````{}<CR>```<Esc>klla
" vimwiki create table
autocmd FileType vimwiki nnoremap <Leader>mt :VimwikiTable<CR>
" Rmarkdown prelude
autocmd FileType vimwiki nnoremap <Leader>mm ggI---<CR>title: <++><CR>fontsize: 12pt<CR>geometry: margin=0.8in<CR>output: pdf_document<CR>---<Esc><<gg
" Add an image with R
autocmd FileType vimwiki nnoremap <Leader>mg I```{r, echo=FALSE, out.width="350px", fig.align="center"}<CR>knitr::include_graphics("<++>")<CR>```<Esc>kk0
"}}}

" Compiling{{{
" R markdown to pdf (in pdf subfolder)
autocmd FileType rmd nmap <silent> <Leader>c :!echo<space>"require(rmarkdown);<space>render('<c-r>%')"<space>\|<space>R<space>--vanilla;mv %:r.pdf %:p:h/pdf/%:t:r.pdf<CR><CR>
" Read HEIGWiki pdf file
autocmd FileType vimwiki nmap <silent> <Leader>e :!zathura ~/Notebooks/HEIGWiki/pdf/%:t:r.pdf 2&> /dev/null &<CR><CR>

" Create pdf from Latex
autocmd FileType tex nmap <buffer> <silent> <Leader>c :!pdflatex % && biber %:r && pdflatex %<CR><CR>
" Open LaTeX PDF file in zathura
nmap <silent> <Leader>e :!zathura %:r.pdf 2&> /dev/null &<CR><CR>

" Python
autocmd FileType python nmap <buffer> <Leader>c :!tmux send-keys -t right "python %" C-m<CR><CR>

" Java
autocmd FileType java nmap <buffer> <Leader>c :!tmux send-keys -t right "javac %" C-m<CR><CR>
autocmd FileType java nmap <buffer> <Leader>r :!tmux send-keys -t right "rm -R target/*" C-m<CR><CR>
autocmd FileType java nmap <buffer> <Leader>e :!tmux send-keys -t right "java %:r" C-m<CR><CR>
autocmd FileType java nmap <buffer> <Leader>m :!tmux send-keys -t right "mvn clean test" C-m<CR><CR>

" gcc, g++ compiler{{{
" g++
autocmd FileType cpp,hpp,h nmap <buffer> <Leader>cc :!g++ *.cpp -Wall -Wconversion -Wextra -pedantic -std=c++11 -o bin/main.out<CR><CR>
" -- Makefile
autocmd FileType cpp,hpp,h nmap <buffer> <Leader>cm :!make<CR>
" -- Compile for debugging
autocmd FileType cpp,hpp,h nmap <buffer> <Leader>cd :!g++ *.cpp -g -O0 -std=c++11 -o bin/%:r_debug.out<CR><CR>
" gcc
autocmd FileType c nmap <buffer> <Leader>cc :!gcc % -Wall -Wconversion -Wextra -pedantic -std=c11 -lm -o bin/%:r.out<CR><CR>
autocmd FileType c nmap <buffer> <Leader>ca :!gcc *.c -Wall -Wconversion -Wextra -pedantic -std=c11 -lm -o bin/%:r.out<CR><CR>
autocmd FileType c nmap <buffer> <Leader>cE :!gcc -E % -o extendedsrc.i<CR><CR>:e extendedsrc.i<CR>

" Run current file's binary
autocmd FileType cpp,c nmap <Leader>e :!tmux send-keys -t right ./bin/main.out C-m<CR><CR>
" clean binaries
autocmd FileType cpp,hpp,c,h nmap <buffer> <Leader>cq :!rm bin/*.out<CR><CR>
"}}}
"}}}
"}}}

" Custom functions{{{
command Vconf e ~/Dev/dotfiles/vim/vimrc

" Write when the file wasn't opened with sudo privileges
cmap w!! w !sudo tee % > /dev/null

" Insert snippets
command SnipCpp 0r ~/Dev/dotfiles/vim/snippets/CPPLab.txt
command SnipPython 0r ~/Dev/dotfiles/vim/snippets/Python.txt
command SnipRmdHeaders r ~/Dev/dotfiles/vim/snippets/RmdAdvanced.txt
command SnipLatexStart 0r ~/Dev/dotfiles/vim/snippets/Latex.txt
command SnipLatexGraph r ~/Dev/dotfiles/vim/snippets/LatexGraph.txt
"}}}

" Tab config (when editorconfig not in use) {{{
" set tabstop=8 " default
set softtabstop=4
set shiftwidth=4
set expandtab
"}}}

" Code folding {{{
set foldmethod=marker " Fold based on markers
set foldnestmax=5     " 5 levels deep folds
set foldenable        " Enable folding
set foldlevel=99      " Leave folds open by default

autocmd FileType vim set foldlevel=0   " Close all folds by default

" Spacebar to open/close folds in normal mode,
" and also to create new ones in visual mode
nnoremap <silent> <Space> @=(foldlevel('.')?'za':"\<Space>")<CR>
vnoremap <Space> zf
"}}}
