# Path to your oh-my-zsh installation.
export ZSH=/home/luc/.oh-my-zsh

# Themes (random, agnoster, bira, bureau, gallois)
# ZSH_THEME="agnoster"
# Parth's prompt
source $HOME/Dev/dotfiles/zsh/prompt.sh

# Plugins
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git laravel5 colored-man-pages colorize z zsh-syntax-highlighting zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

HYPHEN_INSENSITIVE="true"
export EDITOR='vim'

# Aliases {{{
alias l="ls -ah --group-directories-first"
alias ll="ls -lhaF --color=auto --group-directories-first"
alias cl="clear;ls -h --group-directories-first"

alias s="sudo"
alias v="vim"
alias g="git"
alias gs="git status"
alias gl="git log"
alias ga="git add ."
alias gc="git commit"
alias gp="git push origin master"

alias composer="/usr/local/bin/composer.phar"
alias laravel="~/.config/composer/vendor/bin/laravel"

alias fanmin="clevo-indicator 40"
alias fanlow="clevo-indicator 45"
alias fanmiddle="clevo-indicator 50"
alias fanhigh="clevo-indicator 55"
alias mp3-dl="youtube-dl --audio-quality 1 --extract-audio --audio-format mp3"

alias cdev="cd ~/Dev/"
alias cdot="cd ~/Dev/dotfiles/"
alias cdoc="cd ~/Documents/"
alias cnotes="cd ~/Documents/Notebooks/"
alias cwww="cd ~/Shortcuts/web/www/"
alias cshort="cd ~/Shortcuts/"
alias ,q="exit"
alias help="man"

alias dp="dpkg -l | grep "
alias aptl="apt list --upgradable"
alias apts="apt search"
alias aptupd="sudo apt update"
alias aptupg="sudo apt upgrade"
alias apti="sudo apt install"

alias tm="tmux attach -t base || tmux new -s base"
alias tl="tmux ls"
alias tn="tmux new -s "
alias tk="tmux kill-session -t "
# }}}

# Bindings{{{
# Executes ls on dir change
chpwd() ls -h --group-directories-first

# git
	function git_prepare() {
		if [ -n "$BUFFER" ];
			then
				BUFFER="git add -A; git commit -m \"$BUFFER\" && git push"
		fi

		if [ -z "$BUFFER" ];
			then
				BUFFER="git add -A; git commit -v && git push"
		fi

		zle accept-line
	}
	zle -N git_prepare
	bindkey "^g" git_prepare

# home
	function goto_home() {
		BUFFER="cd ~/"$BUFFER
		zle end-of-line
		zle accept-line
	}
	zle -N goto_home
	bindkey "^b" goto_home

# Edit and rerun
	function edit_and_run() {
		BUFFER="fc"
		zle accept-line
	}
	zle -N edit_and_run
	bindkey "^v" edit_and_run

# LS
	function ctrl_l() {
		BUFFER="cl"
		zle accept-line
	}
	zle -N ctrl_l
	bindkey "^q" ctrl_l

# Sudo
	function add_sudo() {
		BUFFER="sudo !!"
		zle end-of-line
	}
	zle -N add_sudo
	bindkey "^s" add_sudo
# }}}

# Launch tmux with screen-256color
# if [[ -n "$TMUX" ]] && [[ ! -e "/root/.automatic_start_occurred" ]];then
# 	export TERM=screen-256color
# fi
