# Path to your oh-my-zsh installation.
export ZSH=/home/luc/.oh-my-zsh

# History size
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE

# Themes (random, agnoster, bira, bureau, gallois)
# ZSH_THEME="avit"
# Parth's prompt (gallois-like)
source $HOME/Dev/dotfiles/zsh/prompt.sh

# Plugins
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git virtualenv colored-man-pages colorize z zsh-syntax-highlighting zsh-autosuggestions)

# Config
source $ZSH/oh-my-zsh.sh

VIRTUAL_ENV_DISABLE_PROMPT=0
HYPHEN_INSENSITIVE="true"
export EDITOR='vim'
export CHEATCOLORS=true

# Set CapsLock to act as Escape on tap and Ctrl on hold
setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape'

# Aliases
# source /etc/zsh/zshenv
source $HOME/Dev/dotfiles/zsh/aliases

# Functions
source $HOME/Dev/dotfiles/zsh/functions

# Executes ls on dir change
chpwd() ls -v --group-directories-first

# Control functions{{{
# git
function git_prepare() {
	if [ -n "$BUFFER" ];
		then
			BUFFER="git add -A; git commit -m \"$BUFFER\" && git push"
	fi

	if [ -z "$BUFFER" ];
		then
			BUFFER="git add -A; git commit -v && git push"
	fi

	zle accept-line
}
zle -N git_prepare
bindkey "^g" git_prepare

# home
function go_back() {
	BUFFER="cd .."
	# zle end-of-line
	zle accept-line
}
zle -N go_back
bindkey "^b" go_back

# Edit and rerun
function edit_and_run() {
	BUFFER="fc"
	zle accept-line
}
	zle -N edit_and_run
	bindkey "^v" edit_and_run

# LS
	function ctrl_l() {
		BUFFER="cl"
		zle accept-line
	}
	zle -N ctrl_l
	bindkey "^w" ctrl_l

# Sudo
	function add_sudo() {
		BUFFER="sudo !!"
		zle end-of-line
	}
	zle -N add_sudo
	bindkey "^s" add_sudo
# }}}
